.github/workflows/main.yaml, packages/fancy_logger/pubspec.yaml, packages/nekoton_repository/pubspec.yaml, pubspec.lock, pubspec.yaml, test/counter/view/counter_page_test.dart
=> fix: ugrade flutter

melos.yaml, packages/fancy_logger/lib/src/db_logger.dart, packages/fancy_logger/lib/src/fancy_logger.dart, packages/fancy_logger/test/src/db_logger_test.dart
Added ability to set custom filename for exported logs.
=> feat: add ability to set custom filename

.github/workflows/storybook-gh-pages-deploy.yaml
=> fix: add gh flutter action

.github/workflows/storybook-gh-pages-deploy.yaml, packages/ui_components_lib/example/.gitignore, packages/ui_components_lib/example/pubspec.yaml, pubspec.lock, scripts/build-storybook.sh
Fix build and deploy storybook
=> fix: storypook (uikit) base path

.github/workflows/storybook-gh-pages-deploy.yaml
Fix storybook automated changleg extraction from git log.
=> fix: uikit storybook git changelog

lib/app/router/page_transitions.dart, lib/app/router/router.dart, lib/feature/browser/view/browser_view.dart, lib/feature/profile/view/profile_view.dart, lib/feature/wallet/view/wallet_view.dart
Add transition animation for navigation between onboarding and root page, plus tab changing.
https://user-images.githubusercontent.com/3867874/233157821-a09de005-16bd-44bf-bac3-aec0e2c3b193.mov
=> feat: add navigation transition animation

.github/PULL_REQUEST_TEMPLATE.md
=> feat: add copilot4prs

pubspec.lock, pubspec.yaml
=> feat: upgrade go_router

.github/workflows/app-deploy.yaml, .github/workflows/storybook-gh-pages-deploy.yaml, .github/workflows/version.yaml
Add automated versioning using 'melos version' feature.
=> feat: add automated versioning

.github/workflows/version.yaml
Another attempt to trigger checks. I dunno why, but it still can't trigger checks after version bump PR.
=> fix: another attempt to trigger checks

.github/workflows/app-deploy.yaml, .github/workflows/main.yaml, .github/workflows/storybook-gh-pages-deploy.yaml, .github/workflows/version.yaml
=> fix: flutter version

lib/app/router/app_route.dart, lib/feature/widgets/default_app_bar.dart
We should use go_router in any navigation action.
=> fix: use go_router pop

pubspec.lock, pubspec.yaml
Just update some libs (thnx, dependabot!).
=> chore: update libs

.gitignore, android/fastlane/Fastfile, ios/fastlane/Fastfile, scripts/build-storybook.sh, scripts/clean.sh, scripts/deploy/fad-apk.sh, scripts/deploy/fad-ipa.sh, scripts/get-changelog.sh, test/tools/get_build_number_test.dart
Made the log more concise, added character filtering.
=> fix: changelog generator for releases

.github/workflows/app-deploy.yaml, .github/workflows/main.yaml, .github/workflows/storybook-gh-pages-deploy.yaml, .github/workflows/version.yaml, ios/Runner.xcodeproj/project.pbxproj, lib/bootstrap/logger.dart, lib/feature/onboarding/widgets/onboarding_background.dart, packages/encrypted_storage/pubspec.yaml, packages/fancy_logger/pubspec.yaml, packages/nekoton_repository/pubspec.yaml, packages/ui_components_lib/example/lib/main.dart, packages/ui_components_lib/example/pubspec.lock, packages/ui_components_lib/example/pubspec.yaml, packages/ui_components_lib/lib/components/input/common_switch_input.dart, packages/ui_components_lib/lib/ui_components_lib.dart, packages/ui_components_lib/pubspec.yaml, pubspec.lock, pubspec.yaml
Flutter, dart and some libs upgrade.
=> refactor: flutter dart and some libs upgrade

lib/feature/add_seed/check_seed_phrase/widgets/check_seed_answers_widget.dart, lib/feature/add_seed/check_seed_phrase/widgets/check_seed_available_answers_widget.dart, lib/feature/add_seed/create_seed/view/create_seed_view.dart, lib/feature/add_seed/enter_seed_phrase/view/enter_seed_phrase_view.dart, packages/ui_components_lib/lib/components/button/tab_bar.dart, packages/ui_components_lib/lib/components/common/common_card.dart, packages/ui_components_lib/lib/components/common/container/container_column.dart, packages/ui_components_lib/lib/components/common/container/container_row.dart, packages/ui_components_lib/lib/components/common/container/separated_column.dart, packages/ui_components_lib/lib/components/common/container/separated_row.dart, packages/ui_components_lib/lib/components/input/selection_status_input.dart
Refactor ContainerColumn, ContainerRow, SeparatedColumn and SeparatedRow to simplify use of them.
=> refactor: Container* and Separated*

packages/nekoton_repository/lib/src/models/seed_key.dart, packages/nekoton_repository/lib/src/repositories/seed_repository/seed_repository_impl.dart, packages/nekoton_repository/pubspec.yaml, pubspec.lock
Just upgrade nekoton_bridge and fix some naming for compatibility.
=> chore: upgrade nekoton_bridge

packages/encrypted_storage/pubspec.yaml, packages/fancy_logger/pubspec.yaml, packages/nekoton_repository/pubspec.yaml, packages/ui_components_lib/example/pubspec.lock, pubspec.lock, pubspec.yaml
Upgrade go_router and some other libs. Seems like it's still working :)
=> chore: upgrade go_router and some other libs

ios/Runner.xcodeproj/project.pbxproj
Just fix iOS profiles for local developing.
=> fix: ios profiles

lib/app/router/app_route.dart, lib/app/router/page_transitions.dart, lib/feature/root/view/root_view.dart, packages/ui_components_lib/lib/components/button/press_scale_widget.dart, packages/ui_components_lib/lib/components/common/squircle/squircle_shape_factory.dart, packages/ui_components_lib/lib/constants.dart
Show/hide pages depending on isBottomNavigationBarVisible in current route. Also, move Duration constants to ui lib.
=> refactor: hide bottom nav bar on certain pages

lib/app/router/app_route.dart, lib/app/router/page_transitions.dart, lib/app/router/router.dart, lib/app/service/navigation/service/navigation_service.dart, lib/app/service/navigation/widget/navigation_service_widget.dart, pubspec.lock, pubspec.yaml
This PR provides several routing-related things such as:
* Upgrade GoRouter to 9.0.0
* Persist subroutes after root route switching
* Add isSaveSubroutes for root routes
=> refactor: persist subroutes, upgrade GoRouter

lib/app/service/storage_service/nekoton_repository_service.dart, lib/app/service/storage_service/storage_manager_service.dart, lib/app/service/storage_service/storage_service.dart, pubspec.lock, pubspec.yaml
Clear nekoton data on logout by calling NekotonRepository.clear().
=> feat: clear nekoton data on logout

pubspec.lock, pubspec.yaml
This is just a product of merge of two dependabot's PR about freezed and freezed_annotation.
=> chore: upgrade freezed

lib/bootstrap/logger.dart, pubspec.lock, pubspec.yaml
Add version and build number to session start event in logs. It will simplify debugging.
=> feat: add version and build number to session start event in logs

lib/app/router/app_route.dart, lib/feature/add_seed/enter_seed_name/view/enter_seed_name_page.dart, lib/feature/profile/key_detail/view/key_detail_view.dart, lib/feature/profile/manage_seeds_accounts/view/manage_seeds_accounts_view.dart, lib/feature/profile/seed_detail/view/seed_detail_view.dart
This is just a quick feat/refactor that brings named path and query params to routes.
=> feat: named path and query params

assets/translations/en.json, assets/translations/ko.json, integration_test/migration_test.dart, lib/app/service/migration_service.dart, lib/app/service/storage_service/browser_storage_service.dart, lib/app/service/storage_service/browser_tabs_storage_service.dart, lib/app/service/storage_service/storage_manager_service.dart, lib/app/service/storage_service/storage_service.dart, lib/bootstrap/migrate_storage.dart, lib/feature/browser/bloc/browser_tabs_bloc.dart, lib/feature/browser/bloc/browser_tabs_event.dart, lib/feature/browser/browser_search_bar/browser_search_bar.dart, lib/feature/browser/browser_tab_view/browser_tab_view.dart, lib/feature/browser/primary/primary_view.dart, lib/feature/browser/view/browser_page.dart, packages/ui_components_lib/example/ios/Runner.xcodeproj/project.pbxproj, packages/ui_components_lib/example/lib/stories/inputs.dart, packages/ui_components_lib/lib/components/input/browser_search_bar.dart, packages/ui_components_lib/lib/components/input/common_input.dart, packages/ui_components_lib/lib/components/input/input.dart
This PR adds new BrowserTabsStorageService (refactoring BrowserStorageService).
=> refactor: browser tabs service

lib/feature/browser/browser_search_bar/browser_search_bar.dart, lib/feature/browser/primary/primary_view.dart, packages/ui_components_lib/example/lib/stories/inputs.dart, packages/ui_components_lib/lib/components/input/browser_search_bar.dart, packages/ui_components_lib/lib/components/input/common_input.dart, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Browser search bar: design and functionality
=> feat: browser search bar (with uikit)

pubspec.lock, pubspec.yaml
This PR fixes share_plus version due to bug in 7.10
=> fix: fix share_plus version due to bug in 7.10

assets/translations/en.json, assets/translations/ko.json, lib/feature/browser/bloc/browser_tabs/browser_tabs_bloc.dart, lib/feature/browser/bloc/browser_tabs/browser_tabs_event.dart, lib/feature/browser/bloc/browser_tabs/browser_tabs_state.dart, lib/feature/browser/browser_search_bar/browser_search_bar.dart, lib/feature/browser/browser_tabs_view/browser_start_view.dart, lib/feature/browser/primary/primary_view.dart, packages/ui_components_lib/lib/components/input/browser_search_bar.dart
This PR introduces search-as-you-type behavior for browser start screen (bookmarks and predefined items).
=> feat: browser start view search

lib/app/router/router.dart, lib/app/router/routs/browser/browser.dart, lib/app/router/routs/wallet/wallet.dart, lib/feature/browser/browser_tabs_view/browser_start_view.dart, lib/feature/root/view/root_view.dart, pubspec.lock, pubspec.yaml
Just upgrade go_router to the last version (and fix some breaking changes).
=> chore: upgrade go_router

ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/app/service/currencies_service.dart, lib/bootstrap.dart, packages/ui_components_lib/example/pubspec.lock, pubspec.lock
=> chore: upgrade flutter to 3.13.0

pubspec.lock, pubspec.yaml
=> chore: upgrade libs

lib/feature/browser/browser_tab_view/browser_tab_view.dart, lib/feature/browser/inpage_provider/inpage_provider.dart
Inpage Provider should be instantiated with browser tab and get url updates with the browser.
=> fix: instantiate inpage provider in browser tab state

lib/feature/contact_support/widgets/contact_support/contact_support_email_send.dart, pubspec.yaml
Add timestamp to log file name (because of QA wish)
=> fix: add timestamp to log file name

pubspec.lock, pubspec.yaml
Upgrade encrypted_storage and flutter_secure_storage.
=> chore: upgrade encrypted_storage and flutter_secure_storage

integration_test/migration_test.dart, lib/app/router/app_route.dart, lib/app/router/router.dart, lib/app/service/navigation/bloc/navigation_bloc.dart, lib/app/service/navigation/bloc/navigation_event.dart, lib/app/service/navigation/bloc/navigation_state.dart, lib/app/service/navigation/service/navigation_service.dart, lib/app/service/navigation/service/navigation_service_state.dart, lib/app/service/navigation/service/service.dart, lib/app/service/navigation/widget/navigation_service_widget.dart, lib/feature/browser/browser_tabs_view/browser_start_view.dart, lib/feature/root/view/root_view.dart
Use fullPath instead of location when constructing current route.
=> fix: use fullPath instead of location in navigation

lib/feature/add_seed/create_password/view/create_seed_password_view.dart
Fix password text field validation algorithm.
=> fix: enter password validation

packages/ui_components_lib/lib/components/displayable/bottom_sheet/common_bottom_sheet.dart
Enable drag handle for all bottom sheets
=> fix: enable drag for all bottom sheets

ios/Podfile, pubspec.lock, pubspec.yaml
=> fix: xcode 17 things

pubspec.lock, pubspec.yaml
Upgrade nekoton_webview (via git dependency).
=> chore: upgrade nekoton_webview

analysis_options.yaml, lib/app/service/messenger/cubit/messenger_cubit.dart, lib/app/service/ntp_service.dart, lib/app/service/service.dart, lib/app/service/staking_service.dart, lib/bootstrap.dart, lib/bootstrap/bootstrap.dart, lib/bootstrap/nekoton.dart, lib/bootstrap/ntp_service.dart, lib/data/models/browser_bookmark_item.dart, lib/data/models/browser_history_item.dart, lib/data/models/browser_tab.dart, lib/feature/browser/browser_tabs_view/browser_start_view.dart, lib/feature/browser/inpage_provider/inpage_provider.dart, lib/feature/contact_support/widgets/contact_support/contact_support_email_send.dart, lib/feature/wallet/staking/view/cancel_unstaking_page.dart, lib/feature/wallet/token_wallet_details/widgets/token_wallet_transaction.dart, lib/feature/wallet/widgets/account_transactions_tab/detail/details_body.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/ton_wallet_transaction_widget.dart, lib/utils/utils.dart, melos.yaml, packages/datetime_avoid_lint/.gitignore, packages/datetime_avoid_lint/CHANGELOG.md, packages/datetime_avoid_lint/README.md, packages/datetime_avoid_lint/analysis_options.yaml, packages/datetime_avoid_lint/lib/datetime_avoid_lint.dart, packages/datetime_avoid_lint/pubspec.yaml, packages/ui_components_lib/pubspec.yaml, pubspec.lock, pubspec.yaml
This PR provides:
* NtpService (provides NTP-synchronized time)
* Custom lint that prevents you to use DateTime.now() and clock.now()
* NtpTime dumy class for .now and .clockNow syntax sugar
* App's NtpTime, NekotonRepository and nekoton bridge receive offset updates periodically (every 1 min), after cold boot and right after app become active.
=> feat: ntp time

lib/app/service/remote/dns_resolve_service.dart, lib/app/service/remote/remote.dart, lib/feature/browser/primary/primary_view.dart
Add DNS resolver to predict user input is and URL or just a search string (and use will be redirected to the search engine).
=> feat: add DNS resolver to predict user input is URL or search string

pubspec.lock, pubspec.yaml
Chore: flutter_inappwebview upgrade
=> chore: flutter_inappwebview upgrade

assets/translations/en.json, assets/translations/ko.json, lib/app/service/migration_service.dart, lib/app/service/storage_service/browser_bookmarks_storage_service.dart, lib/feature/browser/history/history_view.dart
Fix several things:
* add undo when adding browser bookmark
* clear history search when user leaves history page and came back
* hide history search input when history is empty
=> fix: browser related

lib/feature/browser/browser_tab_view/browser_tab_view.dart
Slightly change displayable error messages in the browser.
=> fix: browser error message

integration_test/migration_test.dart, lib/app/service/nekoton_related/connection_service/network_presets.dart
Changed network presets according to QA request.
=> fix: change network presets

integration_test/migration_test.dart, lib/app/service/nekoton_related/connection_service/connection_service.dart, lib/app/service/nekoton_related/connection_service/network_presets.dart, lib/app/service/storage_service/connections_storage_service.dart, lib/bootstrap/logger.dart, lib/data/models/connection_data.dart, lib/feature/network/edit_network/connection_type.dart, lib/feature/network/edit_network/edit_network_view.dart
Network presets now have forced sorting order in order to make update process more simply. Also we always reload presets that can't be edited from code because we want to update them from time to time (maybe?).
=> feat: network presets sort update

packages/datetime_avoid_lint/pubspec.yaml, pubspec.lock
Custom lint related test break down fix.
=> fix: custom lint related test break down

lib/feature/profile/seed_detail/view/seed_detail_view.dart
https://broxus.youtrack.cloud/issue/EWM-201
Добавление разделителя в список
=> fix: add divider for list keys

lib/feature/wallet/widgets/account_transactions_tab/detail/details_item.dart
https://broxus.youtrack.cloud/issue/EWM-208
https://github.com/broxus/ever_wallet_flutter_new/assets/36672245/61f073e6-03bf-49cd-8e95-a40c91fc4819
=> feat: EWM-208 change onLongPress on onPressed for copy by tap

lib/feature/wallet/ton_wallet_send/widgets/transaction_sending_widget.dart
https://broxus.youtrack.cloud/issue/EWM-209
=> feat: add bottom padding for transaction sending widget

lib/feature/wallet/wallet_prepare_transfer/cubit/wallet_prepare_transfer_cubit.dart
=> fix: go to confirm transaction screen

lib/feature/profile/key_detail/widgets/add_new_local_account_type_sheet/add_new_local_account_type_cubit.dart
https://broxus.youtrack.cloud/issue/EWM-200
=> feat: (EWM-200) move position of WalletType

lib/feature/add_seed/enter_seed_phrase/view/enter_seed_phrase_view.dart
https://broxus.youtrack.cloud/issue/EWM-197
=> fix: EWM-197 overflowed text on button

lib/feature/profile/widgets/logout_confirm_sheet.dart
https://broxus.youtrack.cloud/issue/EWM-69
=> feat: (EWM-69) change style of log out bottom sheet 

.github/workflows/app-deploy.yaml, scripts/build-binary/fad-apk.sh, scripts/build-binary/fad-ipa.sh, scripts/build-binary/store-aab.sh, scripts/build-binary/store-ipa.sh, scripts/build-deploy-fad-store.sh, scripts/build-deploy-fad.sh, scripts/build-deploy-store.sh
=> fix: Test Sentry error

lib/app/router/app_route.dart
=> fix: goFurther resultLocation copied with query parameters

packages/ui_components_lib/lib/v2/colors_v2.dart, packages/ui_components_lib/lib/v2/dimens_v2.dart, packages/ui_components_lib/lib/v2/opac_v2.dart, packages/ui_components_lib/lib/v2/predefined_theme_v2.dart, packages/ui_components_lib/lib/v2/text_styles_v2.dart, packages/ui_components_lib/lib/v2/theme_style_v2.dart, packages/ui_components_lib/lib/v2/ui_components_lib_v2.dart
https://www.figma.com/design/r7EnLW6SXh83pnw14B6egg/UI-Kit-%2F-Sparx?node-id=35-10&t=9QrRPUapx2a8K9NF-0
=> feat: create new theme by new design

lib/feature/contact_support/widgets/contact_support/contact_support_sheet.dart, lib/feature/onboarding/screen/welcome/welcome_screen.dart, lib/feature/onboarding/screen/welcome/welcome_screen_wm.dart, packages/ui_components_lib/lib/components/displayable/bottom_sheet/common_bottom_sheet.dart
=> feat: 236 add button on welcome screen

lib/app/service/messenger/message.dart, lib/app/service/messenger/widget/messenger_service_widget.dart, packages/ui_components_lib/example/lib/stories/inputs.dart, packages/ui_components_lib/example/lib/stories/read_only.dart, packages/ui_components_lib/example/lib/stories/snackbar.dart, packages/ui_components_lib/example/lib/stories/v2/toasts.dart, packages/ui_components_lib/lib/components/displayable/snackbar.dart, packages/ui_components_lib/lib/v2/widgets/toasts/toast.dart, packages/ui_components_lib/lib/v2/widgets/toasts/toast_style.dart
=> feat: ewm-247 redesign toasts

lib/feature/add_seed/enter_seed_phrase/view/enter_seed_phrase_view.dart, packages/ui_components_lib/lib/v2/widgets/text_fields/base_text_field.dart
https://stackoverflow.com/a/61537289/12613699
=> fix: ewm-265 fix suggestion on keyboard

lib/feature/profile/widgets/logout_confirm_sheet.dart
=> fix: EWM-266 move old bottom sheet log out on the new

lib/feature/profile/seed_detail/view/seed_detail_view.dart
=> fix: EWM-255 hide add key when the seed has 24 words

lib/feature/add_seed/import_wallet/import_wallet_widget_model.dart
=> fix: EMW-257 fix import 24 words

lib/feature/browser/browser_tab_view/browser_tab_view.dart
=> EWM-263. Remove transparentBackground

lib/feature/browser/browser_tab_view/browser_tab_view.dart
=> Remove transparentBackground: true

lib/app/service/current_accounts_service.dart, lib/bootstrap/feature_services.dart, lib/di/di.config.dart, lib/feature/wallet/add_account/add_account_result/add_account_result_model.dart, lib/feature/wallet/widgets/select_account/select_account_model.dart, lib/feature/wallet/widgets/select_account/select_account_widget.dart
=> feat: EWM-294. Use selected account after reboot app

lib/feature/browser/browser_tabs_view/browser_start_view.dart
=> feat: EWM-252. Always show see all bookmarks button in browser

ios/Pods/Pods.xcodeproj/project.pbxproj, lib/feature/browser/browser_tab_view/browser_tab_view.dart
=> EWM-299. Browser use onLoadResource instead onProgressChanged

README.md
=> Readme. Update long clone repo section

lib/event_bus/events/base_event.dart, lib/event_bus/events/navigation/bottom_navigation_events.dart, lib/event_bus/primary_bus.dart, lib/feature/root/view/root_view.dart, lib/feature/wallet/view/wallet_page_wm.dart, pubspec.lock, pubspec.yaml
We have 3 independent parts of the application.
1) Navigator.
2) Root widget, which is built in the navigator.
3) Wallet, which is built in the navigator.
4) Bottom panel, which is built in the Root widget and changes the tab.
All these parts are not directly related to each other.
2, 3 and 4 points are in the same plane.
You can make a subject, but we only need to notify that there was a click.
That's why I used Eventbus.
=> EWM-302. Press Wallet scroll to top

assets/translations/en.json, assets/translations/ko.json, lib/feature/choose_network/choose_network_screen_model.dart, lib/feature/choose_network/data/choose_network_item_data.dart, lib/feature/choose_network/widgets/choose_network_item.dart, lib/generated/locale_keys.g.dart, pubspec.lock
=>  EWM-304. Choose network screen remove network description

lib/feature/add_seed/enter_seed_phrase/cubit/enter_seed_phrase_cubit.dart, lib/feature/add_seed/import_wallet/import_wallet_widget_model.dart
=> fix: EWM-311. If change words tab - clear inputs

lib/widgets/amount_input/amount_input.dart
=> fix: EWM-317 fix max value

lib/feature/network/edit_network/edit_network_view.dart, lib/feature/wallet/wallet_deploy/clipboard_paste_button.dart, lib/feature/wallet/wallet_deploy/widgets/wallet_deploy_multisig_body.dart, lib/utils/clipboard_utils.dart
=> fix: EWM-305 add clipboard paste button

lib/feature/add_seed/enter_seed_phrase/cubit/enter_seed_phrase_cubit.dart, lib/feature/add_seed/import_wallet/import_wallet_screen.dart, lib/feature/add_seed/import_wallet/import_wallet_widget_model.dart
=> feat: EWM-359

android/app/src/main/AndroidManifest.xml
=> fix: EWM-350 android:roundIcon

lib/feature/browser/browser_tab_view/browser_tab_view.dart, pubspec.lock
=> Update check custom app link

lib/feature/browser/utils.dart, pubspec.lock
=> fix: add TychoTransportStrategy to TransportExtension

pubspec.lock, pubspec.yaml
=> mobile_scanner: 3.4.1

lib/core/logger/logger.dart, lib/runner.dart, pubspec.lock, pubspec.yaml
=> feat: Add the logger

lib/app/router/routs/wallet/wallet.dart, lib/app/service/current_accounts_service.dart, lib/app/service/messenger/service/messenger_service.dart, lib/bootstrap/logger.dart, lib/core/bloc/bloc_mixin.dart, lib/core/wm/context_wm_mixin.dart, lib/feature/add_seed/create_password/view/create_seed_password_page.dart, lib/feature/add_seed/enter_seed_phrase/cubit/enter_seed_phrase_cubit.dart, lib/feature/add_seed/import_wallet/import_wallet_screen_model.dart, lib/feature/browser/browser_tab_view/browser_tab_view.dart, lib/feature/no_internet/no_internet_screen_wm.dart, lib/feature/profile/account_detail/cubit/account_detail_cubit.dart, lib/feature/profile/manage_seeds_accounts/cubit/manage_seeds_accounts_cubit.dart, lib/feature/profile/manage_seeds_accounts/widgets/export_seed_sheet/export_seed_cubit.dart, lib/feature/wallet/new_account/new_account_page.dart, lib/feature/wallet/staking/action_bloc/action_staking_bloc.dart, lib/feature/wallet/staking/bloc/staking_bloc.dart, lib/feature/wallet/token_wallet_details/cubit/token_wallet_details_cubit.dart, lib/feature/wallet/token_wallet_send/bloc/token_wallet_send_bloc.dart, lib/feature/wallet/widgets/account_transactions_tab/account_transactions_tab_cubit.dart, lib/feature/wallet/widgets/select_account/select_account_model.dart, lib/feature/wallet/widgets/wallet_account_actions/wallet_account_actions_cubit.dart, lib/utils/url_utils.dart, lib/v1/feature/add_seed/check_seed_phrase/cubit/check_seed_phrase_cubit.dart, packages/ui_components_lib/lib/components/common/default_app_bar.dart, pubspec.lock
=> fix: sentry errors

lib/feature/browser/browser_tab_view/browser_tab_view.dart, lib/feature/browser/browser_user_agent_utils.dart, pubspec.lock
=> fix: Default user agent

lib/feature/browser/browser_tab_view/browser_tab_view.dart
=> EWM-400. Browser force open tg scheme url

lib/feature/browser/browser_tab_view/browser_tab_view.dart
=> fix: shouldOverrideUrlLoading remove canLaunch

lib/v1/feature/add_seed/create_seed/cubit/create_seed_cubit.dart, pubspec.lock
=> fix: CreateSeedCubit emitSafe

lib/app/router/routs/wallet/wallet.dart, lib/feature/wallet/ton_confirm_transaction/bloc/ton_confirm_transaction_bloc.dart, lib/feature/wallet/ton_confirm_transaction/view/ton_confirm_transaction_confirm_view.dart, lib/feature/wallet/ton_confirm_transaction/view/ton_confirm_transaction_page.dart, lib/feature/wallet/widgets/account_transactions_tab/detail/ton_wallet_multisig_pending_transaction_details.dart, lib/feature/wallet/widgets/token_transfer_info/token_transfer_info_widget.dart, lib/feature/wallet/widgets/token_transfer_info/token_transfer_info_wm.dart, packages/ui_components_lib/lib/components/common/container/container.dart, packages/ui_components_lib/lib/components/common/container/shaped_container.dart, packages/ui_components_lib/lib/components/common/container/shaped_container_column.dart, packages/ui_components_lib/lib/components/common/container/shaped_container_row.dart, pubspec.lock
=> 12 confirm transaction

lib/app/service/connection/connection_service.dart, lib/app/service/connection/data/connection_data/connection_data.dart, lib/app/service/connection/data/connection_data/connection_data.freezed.dart, lib/app/service/connection/data/connection_data/connection_data.g.dart, lib/app/service/connection/mapping/networks_mapper.dart, lib/feature/browser/utils.dart, lib/feature/choose_network/choose_network_screen.dart, lib/feature/choose_network/choose_network_screen_model.dart, lib/feature/network/edit_network/connection_type.dart, lib/feature/network/edit_network/edit_network_view.dart
=> Connection isUsedOnStart

lib/app/service/connection/presets_connection_service.dart, lib/core/exceptions/presets_connections_exceptions.dart
=> Presets error sentry

lib/feature/profile/view/profile_view.dart
=> ProfileView change color

lib/app/router/app_route.dart
=> fix: getRootPath try..catch

scripts/build-binary/fad-apk.sh, scripts/build-binary/fad-ipa.sh, scripts/build-binary/store-aab.sh, scripts/build-binary/store-ipa.sh, scripts/build.sh
=> build: CI. Set main target from flavor

packages/ui_components_lib/lib/components/button/common_button.dart, packages/ui_components_lib/lib/components/button/press_scale_widget.dart, packages/ui_components_lib/lib/components/button/tab_bar.dart, packages/ui_components_lib/lib/components/common/common_chips.dart, packages/ui_components_lib/lib/components/common/default_app_bar.dart, packages/ui_components_lib/lib/components/common/money_widget.dart, packages/ui_components_lib/lib/components/common/switcher/common_tab_swither.dart, packages/ui_components_lib/lib/components/displayable/bottom_sheet/common_bottom_sheet.dart, packages/ui_components_lib/lib/components/displayable/browser_bottom_bar_primary.dart, packages/ui_components_lib/lib/v2/widgets/modals/primary_bottom_sheet.dart, packages/ui_components_lib/lib/v2/widgets/toasts/toast.dart
=> EWM-419. Fix builds in widgets

android/gradle.properties
=> fix: Fix r8 gradle

lib/app/view/app_model.dart
=> AppLifecycleListener create after init

lib/feature/wallet/widgets/account_asset_tab/select_tokens/select_token_wm.dart
=> fix: EWM-383. Select tokens ignore custom tokens knightforce A minute ago

lib/app/service/storage_service/browser_tabs_storage_service.dart, lib/app/service/storage_service/general_storage_service.dart, lib/data/models/browser_tab.dart, lib/feature/browser/approvals_listener/actions/send_message/send_message_wm.dart, lib/feature/browser/approvals_listener/view/approvals_listener_widget.dart, lib/feature/browser/browser_tabs_view/browser_start_view.dart, lib/feature/browser/tabs/tab_view.dart, lib/feature/qr_scanner/cubit/qr_cubit.dart, lib/feature/root/view/root_view.dart, lib/feature/wallet/widgets/account_transactions_tab/account_transactions_tab_cubit.dart, packages/ui_components_lib/lib/components/input/browser_search_bar.dart
=> fix: remove late

assets/configs/connections.json, pubspec.yaml
=> feat: Update config

.github/workflows/app-deploy.yaml
=> Workflow app deploy remove push on test

assets/configs/connections.json
=> feart: Update local connections config

pubspec.yaml
=> fix: flutter_plugin_android_lifecycle: 2.0.24

lib/feature/bootstrap_failed/view/bootstrap_failed_rerun_view.dart
=> feat: BootstrapFailedRerunView contact us button

lib/feature/wallet/widgets/account_transactions_tab/account_transactions_tab.dart, lib/feature/wallet/widgets/account_transactions_tab/detail/details.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/ton_wallet_multisig_expired_transaction/ton_wallet_multisig_expired_transaction_model.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/ton_wallet_multisig_expired_transaction/ton_wallet_multisig_expired_transaction_widget.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/ton_wallet_multisig_expired_transaction/ton_wallet_multisig_expired_transaction_widget_wm.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/ton_wallet_multisig_expired_transaction/widgets/transaction_details.dart, lib/feature/wallet/widgets/account_transactions_tab/widgets/widgets.dart
=> refactor: Ewm 446 ton wallet multisig expired transaction details page on elementary

lib/feature/browser_v2/managers/tabs/tabs_manager.dart, lib/feature/browser_v2/screens/main/browser_main_screen.dart, lib/feature/browser_v2/screens/main/browser_main_screen_wm.dart, lib/feature/browser_v2/screens/main/data/menu_data.dart, lib/feature/browser_v2/screens/main/menu_animation_helper.dart, lib/feature/browser_v2/screens/main/widgets/pages/page/browser_page.dart, lib/feature/browser_v2/screens/main/widgets/pages/page/browser_page_wm.dart, lib/feature/browser_v2/screens/main/widgets/pages/pages_list.dart
=> fix: browser fixes2

lib/widgets/bottom_navigation_bar/custom_bottom_navigation_bar.dart
=> fix(EWM-532) Corners bottom navigation

lib/feature/browser_v1/approvals_listener/actions/widgets/expandable_card.dart, lib/feature/browser_v2/screens/main/widgets/control_panels/navigation_panel/url_action_sheet.dart, lib/feature/browser_v2/screens/main/widgets/groups_menu/widgets/edit_group_name_bottom_sheet.dart, lib/feature/browser_v2/screens/main/widgets/groups_menu/widgets/item.dart, lib/feature/browser_v2/screens/main/widgets/tabs/item/browser_tabs_list_item.dart, lib/feature/browser_v2/screens/main/widgets/tabs/tabs_list/widgets/group_header_item.dart, lib/feature/browser_v2/widgets/bottomsheets/book/widgets/book_item/book_item.dart, lib/feature/browser_v2/widgets/bottomsheets/book/widgets/book_menu.dart, lib/feature/browser_v2/widgets/bottomsheets/book/widgets/history/widgets/clear_history_modal.dart, lib/feature/browser_v2/widgets/bottomsheets/book/widgets/tab_bar.dart, lib/feature/browser_v2/widgets/bottomsheets/browser_main_menu/browser_main_menu.dart, lib/feature/splash/splash_screen.dart, lib/widgets/bottom_navigation_bar/custom_bottom_navigation_bar.dart, lib/widgets/network_icon.dart, packages/ui_components_lib/lib/v2/colors_v2.dart
=> feat(EWM-412): move colors to palette

.github/workflows/app-deploy.yaml
=> feat(EWM-368): add melos analyze and check-format into ci setup

lib/feature/browser_v2/screens/main/widgets/groups_menu/browser_group_menu_wm.dart
=> fix(EWM-535): BrowserGroupMenu. Close when press item
